whitespace    :    targ1     targ2    



	echo Running whitespace tests    




targ1     :         
	       echo			   Successfully        ran          targ1				  
	echo The above line should run with no errors or extra whitespace between words

targ2:
		echo Successfully ran targ2









